# Generated by Django 3.2.5 on 2021-07-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
