# Generated by Django 3.2.5 on 2021-07-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admnNo',
            field=models.IntegerField(default=1234, verbose_name='Admission Number'),
            preserve_default=False,
        ),
    ]
