# Generated by Django 3.2.5 on 2021-07-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_admnno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadharNumber',
            field=models.IntegerField(default=0, verbose_name='Aadhar Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
