# Generated by Django 3.2.5 on 2021-07-03 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210703_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
