# Generated by Django 3.2.5 on 2021-07-03 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_student_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2021, 1, 1, 0, 0), verbose_name='DOB'),
        ),
    ]
