# Generated by Django 3.2.5 on 2021-07-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_student_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feePaidMonth',
            field=models.IntegerField(default=0, verbose_name='No of paid months'),
        ),
    ]
