# Generated by Django 3.2.5 on 2021-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_student_feepaidmonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='feePaidMonth',
        ),
        migrations.AddField(
            model_name='student',
            name='feeStatus',
            field=models.TextField(default='{}', verbose_name='Fee status in JSON format'),
        ),
    ]
