# Generated by Django 3.2.5 on 2021-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_grade_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='className',
            field=models.CharField(blank=True, max_length=5, verbose_name='Class'),
        ),
    ]
