# Generated by Django 3.2.5 on 2021-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210707_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='className',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='Class'),
        ),
    ]
