# Generated by Django 3.2.5 on 2021-07-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_grade_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
