# Generated by Django 3.2.5 on 2021-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_student_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.CharField(blank=True, default='NIL', max_length=10),
        ),
    ]
