# Generated by Django 3.2.5 on 2021-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
