# Generated by Django 3.2.5 on 2021-07-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadharNumber',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Aadhar Number'),
        ),
    ]
