# Generated by Django 3.2.5 on 2021-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_student_aadharnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marksheet',
            field=models.TextField(blank=True, default='{}', verbose_name='Marksheet as Json'),
        ),
    ]
