# Generated by Django 3.2.5 on 2021-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_student_marksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marksheet',
            field=models.TextField(blank=True, default='[]', verbose_name='Marksheet as Json'),
        ),
    ]
