# Generated by Django 3.2.5 on 2021-07-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_student_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.CharField(blank=True, default='0', max_length=8),
        ),
    ]
