# Generated by Django 3.2.5 on 2021-07-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardiansName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathersName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothersName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
